name: Build React on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # React ビルド

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: "AKIA4QYU53CDN27WKJQG"
          AWS_SECRET_ACCESS_KEY: "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"
        run: aws s3 cp --recursive --acl public-read --region ap-northeast-1 build s3://rentalserver-app